spring:
datasource:
url: jdbc:postgresql://localhost:5432/taskflow
username: taskflow
password: taskflow
jpa:
hibernate:
ddl-auto: update
properties:
hibernate:
format_sql: true
show-sql: true

jwt:
secret: "minhaChaveSecretaSuperSegura123"
expiration: 86400000

server:
port: 8080
